services:
  sploder-revival:
    build:
      context: .
      dockerfile: Dockerfile
    image: sploder-revival
    container_name: sploder_revival_prod
    ports:
     - "80:80"
    depends_on:
     - "db"
    volumes:
      # Production volumes - only expose specific writable directories
      - ./src/users:/var/www/html/users:rw
      - ./src/avatar/a:/var/www/html/avatar/a:rw
      - ./src/cache/events.lock:/var/www/html/cache/events.lock:rw
      - ./src/cache/events.xml:/var/www/html/cache/events.xml:rw
      - ./src/config/currentcontest.txt:/var/www/html/config/currentcontest.txt:rw
      - ./src/database/originalmembers.db:/var/www/html/database/originalmembers.db:rw
      - ./src/graphics/gif:/var/www/html/graphics/gif:rw
      - ./src/graphics/png:/var/www/html/graphics/png:rw
      - ./src/graphics/prj:/var/www/html/graphics/prj:rw
      - ./src/legal:/var/www/html/legal:rw
      - ./src/update/temp:/var/www/html/update/temp:rw
      - ./src/update/uploads:/var/www/html/update/uploads:rw
      - ./src/update/currentversion.txt:/var/www/html/update/currentversion.txt:rw
      - ./src/php/verifyscore.php:/var/www/html/php/verifyscore.php:rw
    environment:
      DOMAIN_NAME: https://yourdomain.com
      # Is this website public via a network?
      # If you are running this PRIVATELY, set this to false
      NETWORKED: true

      # If yes, you must provide the source code to comply with the AGPL-3.0 license
      # If you do not provide the source code, you are in violation of the AGPL-3.0 license
      REPOSITORY: https://github.com/Sploder-Saptarshi/sploder-revival

      # Link to your forum
      FORUMS_URL: https://forums.yourdomain.com

      # Your Discord username, where you can be reached
      # This username will be shown in the privacy policy and other pages
      DISCORD_USERNAME: owner

      # Your email, where you can be reached
      # This email will be shown in the privacy policy and other pages
      EMAIL: owner@yourdomain.com

      # DO NOT INCLUDE THE 'https://discord.gg/' PART
      # DO NOT INCLUDE THE 'https://discord.com/invite/' PART
      # example: cHGz362sdC
      DISCORD_INVITE: yourInviteCode
      LAUNCHER_REPOSITORY_URL: https://github.com/Sploder-Saptarshi/Sploder-Launcher
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: sploder
      POSTGRES_USERNAME: sploder 
      POSTGRES_PASSWORD: your_secure_password_here
      POSTGRES_SSLMODE: disable
      ORIGINAL_MEMBERS_DB: originalmembers
      CF_TURNSTILE_SECRET_KEY: 1x0000000000000000000000000000000AA
      CF_TURNSTILE_SITE_KEY: 1x00000000000000000000AA
      DISCORD_CLIENT_ID:
      DISCORD_SECRET_ID:
      DISCORD_SCOPES: identify
      DISCORD_REDIRECT_URL:
      DISCORD_BOT_TOKEN:
      UPLOAD_API_KEY: your_secure_upload_api_key
    restart: unless-stopped
    # Set file permissions for writable directories (only if needed)
    command: >
      sh -c "
        if [ ! -w /var/www/html/users ] || [ ! -w /var/www/html/avatar/a ]; then
          echo 'Setting permissions...'
          chmod -R 777 /var/www/html/users
          chmod -R 777 /var/www/html/avatar/a
          chmod 777 /var/www/html/cache/events.lock
          chmod 777 /var/www/html/cache/events.xml
          chmod 777 /var/www/html/config/currentcontest.txt
          chmod 777 /var/www/html/database/originalmembers.db
          chmod -R 777 /var/www/html/graphics/gif
          chmod -R 777 /var/www/html/graphics/png
          chmod -R 777 /var/www/html/graphics/prj
          chmod -R 777 /var/www/html/legal
          chmod -R 777 /var/www/html/update/temp
          chmod -R 777 /var/www/html/update/uploads
          chmod 777 /var/www/html/update/currentversion.txt
          chmod 777 /var/www/html/php/verifyscore.php
          echo 'Permissions set successfully.'
        else
          echo 'Directories already writable, skipping permissions setup...'
        fi
        cron && exec apache2-foreground
      "

  db:
    image: postgres:17
    container_name: sploder_postgres_prod
    environment:
      POSTGRES_DB: sploder
      POSTGRES_USER: sploder 
      POSTGRES_PASSWORD: your_secure_password_here
    volumes:
      - ./db:/bootstrap  # Mount the backup file into the container
      - postgres_data:/var/lib/postgresql/data  # Persistent storage for the database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sploder -d sploder"]
      interval: 30s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
