services:
  sploder-revival:
    image: sploder-revival
    container_name: sploder_revival
    ports:
     - "8010:80"
    depends_on:
     - "db"
    environment:
      DOMAIN_NAME: http://mydomain.com
      # DO NOT INCLUDE THE 'https://discord.gg/' PART
      # DO NOT INCLUDE THE 'https://discord.com/invite/' PART
      # example: cHGz362sdC
      DISCORD_INVITE: yourInviteCode
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: sploder
      POSTGRES_USERNAME: sploder 
      POSTGRES_PASSWORD: geoff
      POSTGRES_SSLMODE: disable
      ORIGINAL_MEMBERS_DB: originalmembers
      CF_TURNSTILE_SECRET_KEY: 1x0000000000000000000000000000000AA
      CF_TURNSTILE_SITE_KEY: 1x00000000000000000000AA
      DISCORD_CLIENT_ID:
      DISCORD_SECRET_ID:
      DISCORD_SCOPES: identify
      DISCORD_REDIRECT_URL:
      DISCORD_BOT_TOKEN:
  db:
    image: postgres:17
    container_name: sploder_postgres
    environment:
      POSTGRES_DB: sploder
      POSTGRES_USER: sploder 
      POSTGRES_PASSWORD: geoff
    volumes:
      # - ./db:/docker-entrypoint-initdb.d  # Mount the backup file into the container
      - ./db:/bootstrap  # Mount the backup file into the container
      - ./pgdata:/var/lib/postgresql/data  # Persistent storage for the database
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sploder -d sploder"]
      interval: 30s
      retries: 5
volumes:
  pgdata:
    driver: local
